export const authorizedResponse = {
  success: true,
  info: {
    is_logined: true,
    id: 12765,
    email: "yuyukgh@deeple.co.kr",
    nickname: "SCVVS",
    badge: "null",
    isKakao: false,
    image: "jobi_teach",
    iat: 1657166449,
    exp: 1657252849,
    iss: "고초대졸.com",
    sub: "userInfo",
  },
};

export const normalResponse = {
  status: 200,
  success: true,
  data: [
    {
      id: 7251,
      created_time: 1655275369000,
      company_id: 943,
      title: "[원료의약품 생산] 사원 0명 채용",
      start: 1655251200000,
      end: 1656460800000,
      qual_edu: "고졸",
      recru_position: "신입/경력",
      qual_etc: ["신입/경력 5년 이하"],
      recru_type: "정규직",
      recru_step: ["서류전형", "1차면접"],
      recru_sector: "생산/제조/포장/조립",
      XXXXX: 0,
      recru_work: "원료의약품 및 제품 생산/제조\r\n유기 합성 반응을 통한 제조 수행\r\n원료의약품 정제 수행",
      place_province: "인천광역시",
      place_city: "남동구",
      rotation: "주간",
      favor_certi: ["지게차운전"],
      favor_etc: ["화학, 화학공학, 이공계열 전공자", "지게차운전기능사", "운전가능자", "컴퓨터 활용 능력 우수"],
      submit_doc: ["온라인 이력서"],
      etc: ["수습기간 3개월", "근무일시 : 08:30 ~ 17:30"],
      apply_url:
        "https://www.saramin.co.kr/zf_user/jobs/relay/view?rec_idx=43295589&view_type=list&utm_source=gochodaejol_dotcom",
      bookmark: 1,
      view: 154,
      name: "대봉엘에스",
      qual_edu_long: "고졸 이상",
      recru_type_long: "정규직",
      bus: [false, null],
      company_logo_url: "https://d2nnzfahmszi6w.cloudfront.net/company_images/7251/logo.png",
    },
    {
      id: 7566,
      created_time: 1656383065000,
      company_id: 496,
      title: "[스테인리스 생산] 사원 채용",
      start: 1656288000000,
      end: 1657411200000,
      qual_edu: "고졸",
      recru_position: "경력 무관",
      qual_etc: null,
      recru_type: "정규직",
      recru_step: ["서류전형", "1차면접", "2차면접"],
      recru_sector: "생산/제조/포장/조립",
      XXXXX: 0,
      recru_work: "스테인리스 생산 라인",
      place_province: "충청남도",
      place_city: "당진시",
      rotation: "주간",
      favor_certi: null,
      favor_etc: ["유관업종 유경험자"],
      submit_doc: ["온라인 이력서"],
      etc: ["근무일시 : 주 5일(월~금) 07:30 ~ 16:30"],
      apply_url:
        "https://www.saramin.co.kr/zf_user/jobs/relay/view?rec_idx=43392284&view_type=list&utm_source=gochodaejol_dotcom",
      bookmark: 1,
      view: 34,
      name: "황금에스티",
      qual_edu_long: "고졸 이상",
      recru_type_long: "정규직",
      bus: [false, null],
      company_logo_url: "https://d2nnzfahmszi6w.cloudfront.net/company_images/7566/logo.png",
    },
    {
      id: 7572,
      created_time: 1656393426000,
      company_id: 378,
      title: "[설비보전] 사원 채용",
      start: 1656374400000,
      end: 1658448000000,
      qual_edu: "고졸",
      recru_position: "경력 무관",
      qual_etc: null,
      recru_type: "정규직",
      recru_step: ["서류전형", "면접전형"],
      recru_sector: "기계/기계설비",
      XXXXX: 0,
      recru_work: "생산설비 및 유틸리티 시설 유지 관리",
      place_province: "충청북도",
      place_city: "음성군",
      rotation: "주간",
      favor_certi: null,
      favor_etc: ["업무 유경험자"],
      submit_doc: ["온라인 지원서"],
      etc: [
        "근무일시 : 08:00 ~ 17:00",
        "임금 : 월급 평균 300만원 (기본급 220만원, 기타 수당 및 가산 임금) (소정근로시간 240시간)",
      ],
      apply_url:
        "https://www.saramin.co.kr/zf_user/jobs/relay/view?rec_idx=43396381&view_type=list&utm_source=gochodaejol_dotcom",
      bookmark: 1,
      view: 100,
      name: "일진디스플레이",
      qual_edu_long: "고졸 이상",
      recru_type_long: "정규직",
      bus: [false, null],
      company_logo_url: "https://d2nnzfahmszi6w.cloudfront.net/company_images/7572/logo.png",
    },
  ],
  result: "OK",
  statusName: "OK",
};
