export const INTERNAL_URL = {
  MAIN_URL: "/",
  LOGIN_URL: "/login",
  JD_UPLOAD_URL: "/jd/upload",
  JD_LIST_URL: "/jd/list",
  JD_EDIT_URL: "/jd/edit",
  MAIN_BANNER_URL: "/mainbanner",
  JD_TOP_BANNER_URL: "/topbanner",
  ASIDE_BANNER_URL: "/asidebanner",
  COMPANY_UPLOAD_URL: "/company/upload",
  COMPANY_LIST_URL: "/company/list",
  COMPANY_EDIT_URL: "/company/edit",
  VIRAL_BLOG_URL: "/viral/blog",
  VIRAL_INSTA_URL: "/viral/instagram",
  BUSINESS_USER: "/business/user",
  BUSINESS_JD_LIST_URL: "/business/jd/list",
  BUSINESS_COMPANY_LIST_URL: "/business/company/list",
  BUSINESS_FACTORY_LIST_URL: "/business/factory/list",
  BUSINESS_JD_REGISTER_URL: "/business/jd/register",
  BUSINESS_JD_EDIT_URL: "/business/jd/edit",
  BUSINESS_COMPANY_EDIT_URL: "/business/company/edit",
  BUSINESS_FACTORY_REGISTER_URL: "/business/factory/register",
  BUSINESS_FACTORY_EDIT_URL: "/business/factory/edit",
};
