export const INTERNAL_URL = {
  MAIN_URL: "/",
  LOGIN_URL: "/login",
  JD_UPLOAD_URL: "/jd/upload",
  JD_LIST_URL: "/jd/list",
  JD_EDIT_URL: "/jd/edit",
  MAIN_AD_URL: "/ads/main",
  TOP_AD_URL: "/ads/top",
  APP_JD_AD_URL: "/ads/app",
  COMPANY_UPLOAD_URL: "/company/upload",
  COMPANY_LIST_URL: "/company/list",
  COMPANY_EDIT_URL: "/company/edit",
  COMPANY_KEYWORD_URL: "/company/keyword/list",
  COMPANY_KEYWORD_UPLOAD_URL: "/company/keyword/upload",
  VIRAL_BLOG_URL: "/viral/blog",
  VIRAL_INSTA_URL: "/viral/instagram",
  BUSINESS_USER: "/business/user",
  BUSINESS_JD_LIST_URL: "/business/jd/list",
  BUSINESS_JD_REGISTER_URL: (jdIndex: number) => `/business/jd/register/${jdIndex}`,
  BUSINESS_JD_EDIT_URL: (jdIndex: number) => `/business/jd/edit/${jdIndex}`,
  BUSINESS_COMPANY_LIST_URL: "/business/company/list",
  BUSINESS_COMPANY_EDIT_URL: "/business/company/edit",
  BUSINESS_AUTH_LIST_URL: "/business/auth/list",
  FCM_PUSH: "/app/fcm",
  SEARCH_KEYWORD_URL: "/app/search/list",
  SEARCH_KEYWORD_UPLOAD_URL: "/app/search/upload",
};
