import { ResumeEducationDef } from "../type";

export const selector = (educationArr: ResumeEducationDef[]) =>
  educationArr.map((education) => ({
    id: education.id,
    name: education.name,
    educationType: education.education_type,
    graduateType: education.graduate_type,
    isAlternativeTest: education.is_alternative_test,

    isUturn: education.is_uturn,
    startDate: education.start_date,
    endDate: education.end_date,

    grade: education.grade,
    maxGrade: education.max_grade,
    major: education?.major,
    etc: education?.etc,

    firstAttendance: {
      diseaseSchoolAbsent: education.first_attendance?.disease_school_absent,
      diseaseTardy: education.first_attendance?.disease_tardy,
      diseaseLeave: education.first_attendance?.disease_leave,
      diseaseSubjectAbsent: education.first_attendance?.disease_subject_absent,
      unauthorizedSchoolAbsent: education.first_attendance?.unauthorized_school_absent,
      unauthorizedTardy: education.first_attendance?.unauthorized_tardy,
      unauthorizedLeave: education.first_attendance?.unauthorized_leave,
      unauthorizedSubjectAbsent: education.first_attendance?.unauthorized_subject_absent,
      extraSchoolAbsent: education.first_attendance?.extra_school_absent,
      extraTardy: education.first_attendance?.extra_tardy,
      extraLeave: education.first_attendance?.extra_leave,
      extraSubjectAbsent: education.first_attendance?.extra_subject_absent,
      totalClassDays: education.first_attendance?.total_class_days,
      isPerfect: education.first_attendance?.is_perfect,
      description: education.first_attendance?.description,
    },

    secondAttendance: {
      diseaseSchoolAbsent: education.second_attendance?.disease_school_absent,
      diseaseTardy: education.second_attendance?.disease_tardy,
      diseaseLeave: education.second_attendance?.disease_leave,
      diseaseSubjectAbsent: education.second_attendance?.disease_subject_absent,
      unauthorizedSchoolAbsent: education.second_attendance?.unauthorized_school_absent,
      unauthorizedTardy: education.second_attendance?.unauthorized_tardy,
      unauthorizedLeave: education.second_attendance?.unauthorized_leave,
      unauthorizedSubjectAbsent: education.second_attendance?.unauthorized_subject_absent,
      extraSchoolAbsent: education.second_attendance?.extra_school_absent,
      extraTardy: education.second_attendance?.extra_tardy,
      extraLeave: education.second_attendance?.extra_leave,
      extraSubjectAbsent: education.second_attendance?.extra_subject_absent,
      totalClassDays: education.second_attendance?.total_class_days,
      isPerfect: education.second_attendance?.is_perfect,
      description: education.second_attendance?.description,
    },

    thirdAttendance: {
      diseaseSchoolAbsent: education.third_attendance?.disease_school_absent,
      diseaseTardy: education.third_attendance?.disease_tardy,
      diseaseLeave: education.third_attendance?.disease_leave,
      diseaseSubjectAbsent: education.third_attendance?.disease_subject_absent,
      unauthorizedSchoolAbsent: education.third_attendance?.unauthorized_school_absent,
      unauthorizedTardy: education.third_attendance?.unauthorized_tardy,
      unauthorizedLeave: education.third_attendance?.unauthorized_leave,
      unauthorizedSubjectAbsent: education.third_attendance?.unauthorized_subject_absent,
      extraSchoolAbsent: education.third_attendance?.extra_school_absent,
      extraTardy: education.third_attendance?.extra_tardy,
      extraLeave: education.third_attendance?.extra_leave,
      extraSubjectAbsent: education.third_attendance?.extra_subject_absent,
      totalClassDays: education.third_attendance?.total_class_days,
      isPerfect: education.third_attendance?.is_perfect,
      description: education.third_attendance?.description,
    },
  }));

export const selectEducation = (education: ResumeEducationDef) => ({
  id: education.id,
  name: education.name,
  educationType: education.education_type,
  graduateType: education.graduate_type,
  isAlternativeTest: education.is_alternative_test,

  isUturn: education.is_uturn,
  startDate: education.start_date,
  endDate: education.end_date,

  grade: education.grade,
  maxGrade: education.max_grade,
  major: education?.major,
  etc: education?.etc,

  firstAttendance: {
    diseaseSchoolAbsent: education.first_attendance?.disease_school_absent,
    diseaseTardy: education.first_attendance?.disease_tardy,
    diseaseLeave: education.first_attendance?.disease_leave,
    diseaseSubjectAbsent: education.first_attendance?.disease_subject_absent,
    unauthorizedSchoolAbsent: education.first_attendance?.unauthorized_school_absent,
    unauthorizedTardy: education.first_attendance?.unauthorized_tardy,
    unauthorizedLeave: education.first_attendance?.unauthorized_leave,
    unauthorizedSubjectAbsent: education.first_attendance?.unauthorized_subject_absent,
    extraSchoolAbsent: education.first_attendance?.extra_school_absent,
    extraTardy: education.first_attendance?.extra_tardy,
    extraLeave: education.first_attendance?.extra_leave,
    extraSubjectAbsent: education.first_attendance?.extra_subject_absent,
    totalClassDays: education.first_attendance?.total_class_days,
    isPerfect: education.first_attendance?.is_perfect,
    description: education.first_attendance?.description,
  },

  secondAttendance: {
    diseaseSchoolAbsent: education.second_attendance?.disease_school_absent,
    diseaseTardy: education.second_attendance?.disease_tardy,
    diseaseLeave: education.second_attendance?.disease_leave,
    diseaseSubjectAbsent: education.second_attendance?.disease_subject_absent,
    unauthorizedSchoolAbsent: education.second_attendance?.unauthorized_school_absent,
    unauthorizedTardy: education.second_attendance?.unauthorized_tardy,
    unauthorizedLeave: education.second_attendance?.unauthorized_leave,
    unauthorizedSubjectAbsent: education.second_attendance?.unauthorized_subject_absent,
    extraSchoolAbsent: education.second_attendance?.extra_school_absent,
    extraTardy: education.second_attendance?.extra_tardy,
    extraLeave: education.second_attendance?.extra_leave,
    extraSubjectAbsent: education.second_attendance?.extra_subject_absent,
    totalClassDays: education.second_attendance?.total_class_days,
    isPerfect: education.second_attendance?.is_perfect,
    description: education.second_attendance?.description,
  },

  thirdAttendance: {
    diseaseSchoolAbsent: education.third_attendance?.disease_school_absent,
    diseaseTardy: education.third_attendance?.disease_tardy,
    diseaseLeave: education.third_attendance?.disease_leave,
    diseaseSubjectAbsent: education.third_attendance?.disease_subject_absent,
    unauthorizedSchoolAbsent: education.third_attendance?.unauthorized_school_absent,
    unauthorizedTardy: education.third_attendance?.unauthorized_tardy,
    unauthorizedLeave: education.third_attendance?.unauthorized_leave,
    unauthorizedSubjectAbsent: education.third_attendance?.unauthorized_subject_absent,
    extraSchoolAbsent: education.third_attendance?.extra_school_absent,
    extraTardy: education.third_attendance?.extra_tardy,
    extraLeave: education.third_attendance?.extra_leave,
    extraSubjectAbsent: education.third_attendance?.extra_subject_absent,
    totalClassDays: education.third_attendance?.total_class_days,
    isPerfect: education.third_attendance?.is_perfect,
    description: education.third_attendance?.description,
  },
});
