# Set to true to add reviewers to PRs
addReviewers: true

# Set to 'author' to add PR's author as a assignee
addAssignees: author

# A list of reviewers to be added to PRs (GitHub user name)
reviewers:
  - DeepLeHR-Vi
  - DeepLeHR-Ahri
  - DeepLeHR-Mumu

# A number of reviewers added to the PR
# Set 0 to add all the reviewers (default: 0)
numberOfReviewers: 0

# Set to true to add reviewers from different groups to pull requests
useReviewGroups: true

# A list of reviewers, split into different groups, to be added to pull requests (GitHub user name)
reviewGroups:
  groupA:
    - DeepLeHR-Ahri
    - DeepLeHR-Mumu
    - DeepLeHR-Vi
# A list of assignees, overrides reviewers if set
# assignees:

# A number of assignees to add to the PRs
# Set to 0 to add all of the assignees.
# Uses numberOfReviewers if unset.
numberOfAssignees: 0

# A list of keywords to be skipped the process if PR's title include it
skipKeywords:
  - wip
