export const blankPosition = {
  middle: false,
  high: false,
  college: false,
  four: false,
  required_exp: "",
  min_year: null,
  max_year: null,
  required_etc_arr: undefined,
  contract_type: "",
  conversion_rate: null,
  task_main: "",
  task_sub_arr: undefined,
  task_detail_arr: undefined,
  rotation_arr: undefined,
  rotation_etc: null,
  place: {
    type: "",
    address_arr: [],
    factory_arr: [],
    etc: "",
  },
  hire_number: undefined,
  pay_arr: undefined,
  preferred_certi_arr: [],
  preferred_etc_arr: undefined,
};
