export const data = [
  {
    resume_fixed_id: 742,
    user_id: 7517,
    profile: {
      age: 25,
      sex: "남",
      addressCity: "전국",
      finalSchool: "uni",
      isAnonymous: "",
      recruSector: "공무-전기",
      addressProvince: "전국",
    },
    high_school: {
      name: "영진고등학교",
      type: "일반고등학교",
      grade: "5",
      lateDays: "0",
      missDays: "0",
      leaveDays: "0",
      missClasses: "0",
    },
    uni_school: {
      dept: "전기자동화과",
      name: "영남이공대학교",
      grade: "4.19",
      maxGrade: "4.5",
    },
    certi: {
      certificates: [
        {
          name: "전기",
          year: "2020",
          grade: "산업기사",
          month: "9",
          issuer: "0",
        },
        {
          name: "산업안전",
          year: "2020",
          grade: "산업기사",
          month: "11",
          issuer: "0",
        },
        {
          name: "위험물",
          year: "2021",
          grade: "산업기사",
          month: "8",
          issuer: "0",
        },
      ],
      countinfo: {
        a: 0,
        b: 3,
        c: 0,
        d: 0,
        e: 0,
        high_lvl: 0,
      },
    },
    lang: {
      tests: [
        {
          test: "",
          year: "",
          grade: "",
          month: "",
          country: "",
        },
      ],
    },
    career: {
      careers: [
        {
          dept: "",
          detail: "",
          onWork: "",
          company: "",
          endYear: "",
          notShow: "0",
          endMonth: "",
          startYear: "",
          startMonth: "",
          start: "/",
          end: "/",
          duration: "0개월",
        },
      ],
    },
    award: {
      awards: [
        {
          name: "산악협력 공동교육 캠프",
          year: "2017",
          grade: "은상",
          month: "",
          issuer: "공학기술교육혁신 거점센터",
        },
      ],
    },
    etc: {
      etcs: [
        {
          desc: "봉사시간 113시간 ",
        },
      ],
    },
    score_avg: 5,
    timestamp: "2022-03-09 03:01:03",
    user_nickname: "우주먼지2",
    score_average: 5,
    score_count: 4,
  },
  {
    resume_fixed_id: 435,
    user_id: 3231,
    profile: {
      age: 24,
      sex: "남",
      addressCity: "남구",
      finalSchool: "uni",
      isAnonymous: "",
      recruSector: "생산-오퍼레이터",
      addressProvince: "울산광역시",
    },
    high_school: {
      name: "울산공업고등학교",
      type: "특성화고 - 공업계열",
      grade: "3.5",
      lateDays: "",
      missDays: "",
      leaveDays: "",
      missClasses: "",
    },
    uni_school: {
      dept: "화학공학과",
      name: "울산과학대학교",
      grade: "4.0",
      maxGrade: "4.5",
    },
    certi: {
      certificates: [
        {
          name: "대기환경",
          year: "2021",
          grade: "기사",
          month: "12",
          issuer: "0",
        },
        {
          name: "산업안전",
          year: "2022",
          grade: "기사",
          month: "6",
          issuer: "0",
        },
        {
          name: "산업안전",
          year: "2019",
          grade: "산업기사",
          month: "8",
          issuer: "0",
        },
        {
          name: "위험물",
          year: "2019",
          grade: "산업기사",
          month: "5",
          issuer: "0",
        },
        {
          name: "화학분석",
          year: "2017",
          grade: "기능사",
          month: "6",
          issuer: "0",
        },
        {
          name: "환경",
          year: "2016",
          grade: "기능사",
          month: "12",
          issuer: "0",
        },
        {
          name: "위험물",
          year: "2016",
          grade: "기능사",
          month: "12",
          issuer: "0",
        },
      ],
      countinfo: {
        a: 3,
        b: 2,
        c: 2,
        d: 0,
        e: 0,
        high_lvl: 2,
      },
    },
    lang: {
      tests: [
        {
          test: "TOEIC",
          year: "2021",
          grade: "650점",
          month: "12",
          country: "영어",
        },
      ],
    },
    career: {
      careers: [
        {
          dept: "",
          detail: "",
          onWork: "",
          company: "",
          endYear: "",
          notShow: "0",
          endMonth: "",
          startYear: "",
          startMonth: "",
          start: "/",
          end: "/",
          duration: "0개월",
        },
      ],
    },
    award: {
      awards: [
        {
          name: "",
          year: "",
          grade: "",
          month: "",
          issuer: "",
        },
      ],
    },
    etc: {
      etcs: [
        {
          desc: "가스기사,가스기능사 필기합으로 올해 실기 칠예정입니다",
        },
      ],
    },
    score_avg: 5,
    timestamp: "2022-02-14 20:53:05",
    user_nickname: "기름집",
    score_average: 5,
    score_count: 4,
  },
  {
    resume_fixed_id: 535,
    user_id: 3171,
    profile: {
      age: 22,
      sex: "남",
      addressCity: "이천",
      finalSchool: "uni",
      isAnonymous: "1",
      recruSector: "생산-메인트",
      addressProvince: "경기도",
    },
    high_school: {
      name: "대구일마이스터고등학교",
      type: "마이스터고등학교",
      grade: "2.1",
      lateDays: "0",
      missDays: "0",
      leaveDays: "0",
      missClasses: "0",
    },
    uni_school: {
      dept: "기계공학과",
      name: "구미대학교",
      grade: "4.4",
      maxGrade: "4.5",
    },
    certi: {
      certificates: [
        {
          name: "컴퓨터응용밀링",
          year: "2017",
          grade: "기능사",
          month: "12",
          issuer: "0",
        },
        {
          name: "컴퓨터응용선반",
          year: "2018",
          grade: "기능사",
          month: "6",
          issuer: "0",
        },
        {
          name: "공유압",
          year: "2018",
          grade: "기능사",
          month: "6",
          issuer: "0",
        },
        {
          name: "기계가공조립",
          year: "2018",
          grade: "기능사",
          month: "9",
          issuer: "0",
        },
        {
          name: "설비보전",
          year: "2018",
          grade: "기능사",
          month: "9",
          issuer: "0",
        },
        {
          name: "금형",
          year: "2019",
          grade: "기능사",
          month: "4",
          issuer: "0",
        },
        {
          name: "전산응용기계제도",
          year: "2019",
          grade: "기능사",
          month: "4",
          issuer: "0",
        },
        {
          name: "전기",
          year: "2019",
          grade: "기능사",
          month: "7",
          issuer: "0",
        },
        {
          name: "승강기",
          year: "2019",
          grade: "기능사",
          month: "9",
          issuer: "0",
        },
        {
          name: "생산자동화",
          year: "2019",
          grade: "기능사",
          month: "9",
          issuer: "0",
        },
        {
          name: "기계설계",
          year: "2020",
          grade: "산업기사",
          month: "11",
          issuer: "0",
        },
        {
          name: "컴퓨터응용가공",
          year: "2021",
          grade: "산업기사",
          month: "8",
          issuer: "0",
        },
      ],
      countinfo: {
        a: 10,
        b: 2,
        c: 0,
        d: 0,
        e: 0,
        high_lvl: 0,
      },
    },
    lang: {
      tests: [
        {
          test: "",
          year: "",
          grade: "",
          month: "",
          country: "",
        },
      ],
    },
    career: {
      careers: [
        {
          dept: "CNC선반",
          detail: "CNC선반조작",
          onWork: "재직중",
          company: "(주)세신정밀",
          endYear: "2022",
          notShow: "1",
          endMonth: "2",
          startYear: "2019",
          startMonth: "7",
          start: "2019/7",
          end: "2022/2",
          duration: "2년 7개월",
        },
      ],
    },
    award: {
      awards: [
        {
          name: "",
          year: "",
          grade: "",
          month: "",
          issuer: "",
        },
      ],
    },
    etc: {
      etcs: [
        {
          desc: "",
        },
      ],
    },
    score_avg: 5,
    timestamp: "2022-02-20 14:48:12",
    user_nickname: "귀****",
    score_average: 5,
    score_count: 3,
  },
  {
    resume_fixed_id: 397,
    user_id: 6283,
    profile: {
      age: 25,
      sex: "남",
      addressCity: "서산시",
      finalSchool: "uni",
      isAnonymous: "",
      recruSector: "생산-오퍼레이터",
      addressProvince: "충청남도",
    },
    high_school: {
      name: "비전고등학교",
      type: "일반고등학교",
      grade: "2.4",
      lateDays: "1",
      missDays: "",
      leaveDays: "",
      missClasses: "",
    },
    uni_school: {
      dept: "생명화학공학과",
      name: "동양미래대학교",
      grade: "4.14",
      maxGrade: "4.5",
    },
    certi: {
      certificates: [
        {
          name: "위험물",
          year: "2019",
          grade: "산업기사",
          month: "5",
          issuer: "0",
        },
        {
          name: "가스",
          year: "2020",
          grade: "산업기사",
          month: "9",
          issuer: "0",
        },
        {
          name: "산업안전",
          year: "2021",
          grade: "산업기사",
          month: "8",
          issuer: "0",
        },
      ],
      countinfo: {
        a: 0,
        b: 3,
        c: 0,
        d: 0,
        e: 0,
        high_lvl: 0,
      },
    },
    lang: {
      tests: [
        {
          test: "",
          year: "",
          grade: "",
          month: "",
          country: "",
        },
      ],
    },
    career: {
      careers: [
        {
          dept: "",
          detail: "공정운전",
          onWork: "재직중",
          company: "현대오일뱅크",
          endYear: "2022",
          notShow: "0",
          endMonth: "12",
          startYear: "2022",
          startMonth: "2",
          start: "2022/2",
          end: "2022/12",
          duration: "10개월",
        },
      ],
    },
    award: {
      awards: [
        {
          name: "2017 화학공학 대학생 fun&fun festival",
          year: "2017",
          grade: "대상",
          month: "",
          issuer: "한국화학공학회",
        },
        {
          name: "",
          year: "",
          grade: "",
          month: "",
          issuer: "",
        },
      ],
    },
    etc: {
      etcs: [
        {
          desc: "",
        },
      ],
    },
    score_avg: 5,
    timestamp: "2022-02-14 20:53:05",
    user_nickname: "j121017",
    score_average: 5,
    score_count: 3,
  },
  {
    resume_fixed_id: 1143,
    user_id: 478,
    profile: {
      age: 23,
      sex: "남",
      addressCity: "전국",
      finalSchool: "uni",
      isAnonymous: "",
      recruSector: "생산",
      addressProvince: "전국",
    },
    high_school: {
      name: "경기기계공업고등학교",
      type: "특성화고 - 공업계열",
      grade: "3",
      lateDays: "0",
      missDays: "0",
      leaveDays: "0",
      missClasses: "0",
    },
    uni_school: {
      dept: "제철금속과",
      name: "신성대학교",
      grade: "4.28",
      maxGrade: "4.5",
    },
    certi: {
      certificates: [
        {
          name: "자기비파괴검사",
          year: "2017",
          grade: "기능사",
          month: "3",
          issuer: "0",
        },
        {
          name: "열처리기능사",
          year: "2017",
          grade: "기능사",
          month: "12",
          issuer: "0",
        },
        {
          name: "금속재료시험",
          year: "2017",
          grade: "기능사",
          month: "12",
          issuer: "0",
        },
        {
          name: "전기",
          year: "2018",
          grade: "기능사",
          month: "6",
          issuer: "0",
        },
        {
          name: "침투비파괴검사",
          year: "2018",
          grade: "기능사",
          month: "9",
          issuer: "0",
        },
        {
          name: "환경",
          year: "2019",
          grade: "기능사",
          month: "4",
          issuer: "0",
        },
        {
          name: "설비보전",
          year: "2019",
          grade: "기능사",
          month: "12",
          issuer: "0",
        },
        {
          name: "금속재료",
          year: "2020",
          grade: "산업기사",
          month: "9",
          issuer: "0",
        },
        {
          name: "위험물",
          year: "2021",
          grade: "산업기사",
          month: "12",
          issuer: "0",
        },
      ],
      countinfo: {
        a: 7,
        b: 2,
        c: 0,
        d: 0,
        e: 0,
        high_lvl: 0,
      },
    },
    lang: {
      tests: [
        {
          test: "TOEIC",
          year: "2022",
          grade: "570점",
          month: "4",
          country: "영어",
        },
      ],
    },
    career: {
      careers: [
        {
          dept: "",
          detail: "",
          onWork: "",
          company: "",
          endYear: "",
          notShow: "0",
          endMonth: "",
          startYear: "",
          startMonth: "",
          start: "/",
          end: "/",
          duration: "0개월",
        },
      ],
    },
    award: {
      awards: [
        {
          name: "",
          year: "",
          grade: "",
          month: "",
          issuer: "",
        },
      ],
    },
    etc: {
      etcs: [
        {
          desc: "병장 만기전역 / 22년 2학년 2학기 복학예정",
        },
        {
          desc: "1종보통/한국사2급/제선/제강/압연기능사 보유",
        },
        {
          desc: "산업안전/가스 필기합격",
        },
        {
          desc: "목표기업 제철/석화/정유/가스",
        },
      ],
    },
    score_avg: 5,
    timestamp: "2022-04-22 02:07:48",
    user_nickname: "Cardinals",
    score_average: 5,
    score_count: 3,
  },
  {
    resume_fixed_id: 1084,
    user_id: 5610,
    profile: {
      age: 22,
      sex: "남",
      addressCity: "전국",
      finalSchool: "high",
      isAnonymous: "1",
      recruSector: "생산",
      addressProvince: "전국",
    },
    high_school: {
      name: "천안불당고등학교",
      type: "일반고등학교",
      grade: "3.5",
      lateDays: "0",
      missDays: "0",
      leaveDays: "0",
      missClasses: "0",
    },
    uni_school: {
      dept: "",
      name: "",
      grade: "",
      maxGrade: "4.5",
    },
    certi: {
      certificates: [
        {
          name: "위험물",
          year: "2020",
          grade: "기능사",
          month: "5",
          issuer: "0",
        },
        {
          name: "산업안전",
          year: "2021",
          grade: "산업기사",
          month: "11",
          issuer: "0",
        },
        {
          name: "위험물",
          year: "2021",
          grade: "산업기사",
          month: "12",
          issuer: "0",
        },
      ],
      countinfo: {
        a: 1,
        b: 2,
        c: 0,
        d: 0,
        e: 0,
        high_lvl: 0,
      },
    },
    lang: {
      tests: [
        {
          test: "",
          year: "",
          grade: "",
          month: "",
          country: "",
        },
      ],
    },
    career: {
      careers: [
        {
          dept: "",
          detail: "",
          onWork: "",
          company: "",
          endYear: "",
          notShow: "0",
          endMonth: "",
          startYear: "",
          startMonth: "",
          start: "/",
          end: "/",
          duration: "0개월",
        },
      ],
    },
    award: {
      awards: [
        {
          name: "",
          year: "",
          grade: "",
          month: "",
          issuer: "",
        },
      ],
    },
    etc: {
      etcs: [
        {
          desc: "",
        },
      ],
    },
    score_avg: 5,
    timestamp: "2022-04-11 21:26:40",
    user_nickname: "한****",
    score_average: 5,
    score_count: 2,
  },
  {
    resume_fixed_id: 1139,
    user_id: 8354,
    profile: {
      age: 24,
      sex: "남",
      addressCity: "전주",
      finalSchool: "uni",
      isAnonymous: "1",
      recruSector: "공무-생산설비",
      addressProvince: "전라북도",
    },
    high_school: {
      name: "순창고등학교",
      type: "일반고등학교",
      grade: "6",
      lateDays: "",
      missDays: "",
      leaveDays: "",
      missClasses: "1",
    },
    uni_school: {
      dept: "컴퓨터응용기계과",
      name: "한국폴리텍대학 익산캠퍼스",
      grade: "3.8",
      maxGrade: "4.5",
    },
    certi: {
      certificates: [
        {
          name: "컴퓨터응용가공",
          year: "2021",
          grade: "산업기사",
          month: "12",
          issuer: "0",
        },
        {
          name: "산업안전",
          year: "2021",
          grade: "산업기사",
          month: "12",
          issuer: "0",
        },
        {
          name: "지게차",
          year: "2021",
          grade: "기능사",
          month: "12",
          issuer: "",
        },
      ],
      countinfo: {
        a: 1,
        b: 2,
        c: 0,
        d: 0,
        e: 0,
        high_lvl: 0,
      },
    },
    lang: {
      tests: [
        {
          test: "",
          year: "",
          grade: "",
          month: "",
          country: "",
        },
      ],
    },
    career: {
      careers: [
        {
          dept: "프레스 라인 및 사상",
          detail: "프레스 설비 조작 및 사상작업",
          onWork: "정규직",
          company: "길승산업",
          endYear: "2020",
          notShow: "1",
          endMonth: "4",
          startYear: "2019",
          startMonth: "1",
          start: "2019/1",
          end: "2020/4",
          duration: "1년 3개월",
        },
        {
          dept: "판금(분전반 박스 제작, 고압반 패키지 제작)  용접,그라인더, 샤링기, 도장작업 등등 가능 ",
          detail: "분전반 박스 제작(용접,절곡기,등등사용)",
          onWork: "정규직",
          company: "고려전기",
          endYear: "2021",
          notShow: "1",
          endMonth: "9",
          startYear: "2020",
          startMonth: "4",
          start: "2020/4",
          end: "2021/9",
          duration: "1년 5개월",
        },
      ],
    },
    award: {
      awards: [
        {
          name: "",
          year: "",
          grade: "",
          month: "",
          issuer: "",
        },
      ],
    },
    etc: {
      etcs: [
        {
          desc: "차후에 에너지기능사도 준비하여 공무팀도 지원할 생각입니다. 그리고 고등학교 출결에서 결과가 있는데 이유가 대학입시 준비 때문에 학교 진로선생님께 상담 받고 있었습니다. 물론 다른 선생님들께 허락 받아서 출석 인정 해주셨는데 한분이 실수로 출석 누락시켜서 빠졌어요..  이 부분에 대해선 나중에 면접볼때 설명을 할거지만 그전에 서류전형에서 리스크가 커질까봐 걱정이 됩니다.",
        },
      ],
    },
    score_avg: 5,
    timestamp: "2022-04-21 02:17:50",
    user_nickname: "대****",
    score_average: 5,
    score_count: 2,
  },
  {
    resume_fixed_id: 699,
    user_id: 2490,
    profile: {
      age: 27,
      sex: "남",
      addressCity: "사상구",
      finalSchool: "uni",
      isAnonymous: "",
      recruSector: "생산-오퍼레이터",
      addressProvince: "부산광역시",
    },
    high_school: {
      name: "부산전자공업고등학교",
      type: "특성화고 - 공업계열",
      grade: "1.6",
      lateDays: "0",
      missDays: "0",
      leaveDays: "0",
      missClasses: "0",
    },
    uni_school: {
      dept: "신재생전기계열",
      name: "경남정보대학교",
      grade: "4.49",
      maxGrade: "4.5",
    },
    certi: {
      certificates: [
        {
          name: "전기",
          year: "2020",
          grade: "산업기사",
          month: "6",
          issuer: "0",
        },
        {
          name: "전기공사",
          year: "2020",
          grade: "산업기사",
          month: "8",
          issuer: "0",
        },
        {
          name: "산업안전",
          year: "2021",
          grade: "산업기사",
          month: "8",
          issuer: "0",
        },
        {
          name: "전기",
          year: "2018",
          grade: "기능사",
          month: "9",
          issuer: "0",
        },
        {
          name: "전자기기",
          year: "2014",
          grade: "기능사",
          month: "7",
          issuer: "0",
        },
        {
          name: "전자계산기",
          year: "2013",
          grade: "기능사",
          month: "6",
          issuer: "0",
        },
      ],
      countinfo: {
        a: 3,
        b: 3,
        c: 0,
        d: 0,
        e: 0,
        high_lvl: 0,
      },
    },
    lang: {
      tests: [
        {
          test: "",
          year: "",
          grade: "",
          month: "",
          country: "",
        },
      ],
    },
    career: {
      careers: [
        {
          dept: "",
          detail: "",
          onWork: "",
          company: "",
          endYear: "",
          notShow: "0",
          endMonth: "",
          startYear: "",
          startMonth: "",
          start: "/",
          end: "/",
          duration: "0개월",
        },
      ],
    },
    award: {
      awards: [
        {
          name: "",
          year: "",
          grade: "",
          month: "",
          issuer: "",
        },
      ],
    },
    etc: {
      etcs: [
        {
          desc: "",
        },
      ],
    },
    score_avg: 5,
    timestamp: "2022-03-04 20:32:01",
    user_nickname: "타바코주스",
    score_average: 5,
    score_count: 2,
  },
  {
    resume_fixed_id: 482,
    user_id: 6317,
    profile: {
      age: 31,
      sex: "남",
      addressCity: "전국",
      finalSchool: "high",
      isAnonymous: "1",
      recruSector: "설비-전력설비",
      addressProvince: "전국",
    },
    high_school: {
      name: "수도전기공업고등학교",
      type: "특성화고 - 공업계열",
      grade: "3",
      lateDays: "0",
      missDays: "0",
      leaveDays: "0",
      missClasses: "0",
    },
    uni_school: {
      dept: "",
      name: "",
      grade: "",
      maxGrade: "4.5",
    },
    certi: {
      certificates: [
        {
          name: "전기",
          year: "2020",
          grade: "기사",
          month: "12",
          issuer: "0",
        },
        {
          name: "전기공사",
          year: "2021",
          grade: "기사",
          month: "6",
          issuer: "0",
        },
        {
          name: "컴퓨터활용능력",
          year: "2021",
          grade: "1급",
          month: "1",
          issuer: "",
        },
        {
          name: "ITQ(MS워드, 아래한글, 엑셀, 파워포인트)",
          year: "2019",
          grade: "마스터 A급",
          month: "6",
          issuer: "",
        },
        {
          name: "한국사능력시험",
          year: "2021",
          grade: "2급",
          month: "10",
          issuer: "",
        },
      ],
      countinfo: {
        a: 0,
        b: 0,
        c: 2,
        d: 0,
        e: 0,
        high_lvl: 2,
      },
    },
    lang: {
      tests: [
        {
          test: "TOEIC",
          year: "2022",
          grade: "825점",
          month: "2",
          country: "영어",
        },
      ],
    },
    career: {
      careers: [
        {
          dept: "품질관리팀(차단기검사)",
          detail:
            "귝내 및 국외의 변전소와 발전소에 설치된 GIS 현장시험 밑 유지보수 업무",
          onWork: "정규직",
          company: "효성중공업",
          endYear: "2020",
          notShow: "1",
          endMonth: "3",
          startYear: "2011",
          startMonth: "1",
          start: "2011/1",
          end: "2020/3",
          duration: "9년 2개월",
        },
      ],
    },
    award: {
      awards: [
        {
          name: "",
          year: "",
          grade: "",
          month: "",
          issuer: "",
        },
      ],
    },
    etc: {
      etcs: [
        {
          desc: "",
        },
      ],
    },
    score_avg: 5,
    timestamp: "2022-02-16 12:03:25",
    user_nickname: "으****",
    score_average: 5,
    score_count: 2,
  },
];
