import { INTERNAL_URL } from "@/constants";

export const PROTECTED_ROUTE_ARR = [
  INTERNAL_URL.MY_PAGE,
  INTERNAL_URL.JD_LIST,
  INTERNAL_URL.JD_UPLOAD,
  INTERNAL_URL.FACTORY_LIST,
  INTERNAL_URL.COMPANY_EDIT,
  INTERNAL_URL.MANAGER_LIST,
  INTERNAL_URL.ALARM_LIST,
  INTERNAL_URL.NOTICE_LIST,
  INTERNAL_URL.HELP,
];
