import { INTERNAL_URL } from "../../../pages/constants";

export const THEME_WHITE_PAGES = [
  INTERNAL_URL.SEARCH,
  INTERNAL_URL.COMPANY_DETAIL,
  INTERNAL_URL.JDS_DETAIL,
  INTERNAL_URL.JDS_LIST,
];
