export const BLANK_JD = {
  process_arr: [{ value: "" }, { value: "" }],
  apply_route_arr: [{ value: "" }],
  etc_arr: "",
  middle: false,
  high: false,
  college: false,
  four: false,
  required_exp: "",
  min_year: null,
  max_year: null,
  required_etc_arr: "",
  contract_type: "",
  conversion_rate: null,
  task_main: "",
  task_sub_arr: [],
  task_detail_arr: "",
  rotation_arr: [],
  rotation_etc: null,
  place: {
    type: "일반",
    address_arr: null,
    factory_arr: null,
    etc: null,
  },
  hire_number: null,
  pay_arr: "",
  preferred_certi_arr: null,
  preferred_etc_arr: "",
};

export const JD_UPLOAD_MESSAGE_OBJ = {
  UPLOAD: "최종 공고 업로드 요청 하시겠습니까? 영업일 기준 검수 완료까지 1시간 정도 소요됩니다.",
  LEAVE: "변경사항이 있습니다. 페이지를 나가시겠습니까?",
};
