export const INTERNAL_URL = {
  HOME: "/",
  MY_PAGE: "/mypage",
  JD_LIST: "/jd/list",
  JD_UPLOAD: "/jd/upload",
  JD_EDIT: (jdIndex: number) => `/jd/${jdIndex}/edit`,
  FACTORY_LIST: "/factory/list",
  COMPANY_EDIT: "/company/edit",
  MANAGER_LIST: "/manager/list",
  COMPANY_AUTH: "/company/auth",
  HELP: "/help",
  ALARM_LIST: "/alarm/list",
  ALARM_SETTING: "/alarm/setting",
  NOTICE_LIST: "/notice/list",
  NOTICE_DETAIL: (noticeId: number) => `/notice/detail/${noticeId}`,
  NOT_FOUND: "/404",
  UNKNOWN_ERROR: "/500",
  LOGIN: "/login",
  SIGNUP: "/signup",
  FIND_ID: "/find/id",
  FIND_PASSWORD: "/find/password",
} as const;
