import { INTERNAL_URL } from "@/constants/url";

export const PROTECTED_ROUTE_ARR = [
  INTERNAL_URL.MY_PAGE,
  INTERNAL_URL.JD_LIST,
  INTERNAL_URL.JD_UPLOAD,
  INTERNAL_URL.FACTORY_LIST,
  INTERNAL_URL.COMPANY_EDIT,
  INTERNAL_URL.RECRUITER_LIST,
  INTERNAL_URL.HELP,
];
