import checkIconImage from "shared-image/global/common/yellow_check.svg";

export const carouselArr = [
  {
    id: 1,
    topDesc: "OPEN",
    middleDesc: "고초대졸닷컴",
    title: "웹사이트 전체 리뉴얼",
    lastDesc: "열심히 준비했습니다",
    iconImage: checkIconImage,
    backgroundColor: "#121012",
    buttonObj: {
      target: "_self" as const,
      text: "자세히보기",
      color: "#fff",
      backgroundColor: "#333",
      url: "/event/renewal",
    },
  },
  {
    id: 2,
    topDesc: " ",
    middleDesc: "코닝정밀소재",
    title: "2023년 코닝정밀소재 제조직[기간제] 채용",
    lastDesc: "2022.12.16~2023.01.01",
    backgroundColor: "#030f16",
    buttonObj: {
      target: "_self" as const,
      text: "자세히보기",
      color: "#fff",
      backgroundColor: "#333",
      url: "/jd/detail/12127",
    },
  },
  {
    id: 3,
    topDesc: "OPEN",
    middleDesc: "고초대졸닷컴",
    title: "공고에서 근무할 공장 정보 바로보기 서비스 시작",
    lastDesc: "이제 공장정보는 공고에서 바로 확인하세요!",
    iconImage: checkIconImage,
    backgroundColor: "#2961CD",
    buttonObj: null,
  },
  {
    id: 4,
    topDesc: "OPEN",
    middleDesc: "고초대졸닷컴",
    title: "생산/기능직 관련 최대 규모 오픈카톡방",
    lastDesc: "다양한 취업정보 및 꿀팁을 물어보세요",
    iconImage: checkIconImage,
    backgroundColor: "#fbc540",
    buttonObj: {
      target: "_blank" as const,
      text: "오픈카톡 바로가기",
      color: "#fff",
      backgroundColor: "#333",
      url: "https://open.kakao.com/o/gxquBCud",
    },
  },
];