export const FUNNEL = {
  JD_LIST: "enter_jd_list",
  EXPIRED_JD_LIST: "enter_jd_explist",
  JD_DETAIL: "enter_jd_detail",
  COMPANY_INFO: "enter_company_info",
  COMPANY_JD: "enter_comapany_jd",
  TIP_LIST: "enter_tip_list",
  MY_SPEC_LIST: "enter_my_spec",
  SPEC_LIST: "enter_spec_list",
  REGISTER_SPEC: "enter_spec_register",
  MYPAGE: "enter_mypage",
  POSTING_LIST: "enter_posting_list",
  HOME: "enter_home",
  SEARCH_PAGE: "enter_search_result",
  WELCOME: "enter_welcome",
  NOT_FOUND: "enter_404",
  UNKNOWN_ERROR: "enter_500",
};
