import { ResumeHighSchoolDef } from "../type";

export const selector = (highSchool: ResumeHighSchoolDef) => ({
  id: highSchool.id,
  name: highSchool.name,
  graduateType: highSchool.graduate_type,
  isAlternative_test: highSchool.is_alternative_test,
  startDate: highSchool.start_date,
  endDate: highSchool.end_date,
  firstAttendance: {
    diseaseSchoolAbsent: highSchool.first_attendance?.disease_school_absent,
    diseaseTardy: highSchool.first_attendance?.disease_tardy,
    diseaseLeave: highSchool.first_attendance?.disease_leave,
    diseaseSubject_absent: highSchool.first_attendance?.disease_subject_absent,
    unauthorizedSchoolAbsent: highSchool.first_attendance?.unauthorized_school_absent,
    unauthorizedTardy: highSchool.first_attendance?.unauthorized_tardy,
    unauthorizedLeave: highSchool.first_attendance?.unauthorized_leave,
    unauthorizedSubject_absent: highSchool.first_attendance?.unauthorized_subject_absent,
    extraSchoolAbsent: highSchool.first_attendance?.extra_school_absent,
    extraTardy: highSchool.first_attendance?.extra_tardy,
    extraLeave: highSchool.first_attendance?.extra_leave,
    extraSubject_absent: highSchool.first_attendance?.extra_subject_absent,
    totalClass_days: highSchool.first_attendance?.total_class_days,
    isPerfect: highSchool.first_attendance?.is_perfect,
    description: highSchool.first_attendance?.description,
  },
  secondAttendance: {
    diseaseSchoolAbsent: highSchool.second_attendance?.disease_school_absent,
    diseaseTardy: highSchool.second_attendance?.disease_tardy,
    diseaseLeave: highSchool.second_attendance?.disease_leave,
    diseaseSubject_absent: highSchool.second_attendance?.disease_subject_absent,
    unauthorizedSchoolAbsent: highSchool.second_attendance?.unauthorized_school_absent,
    unauthorizedTardy: highSchool.second_attendance?.unauthorized_tardy,
    unauthorizedLeave: highSchool.second_attendance?.unauthorized_leave,
    unauthorizedSubject_absent: highSchool.second_attendance?.unauthorized_subject_absent,
    extraSchoolAbsent: highSchool.second_attendance?.extra_school_absent,
    extraTardy: highSchool.second_attendance?.extra_tardy,
    extraLeave: highSchool.second_attendance?.extra_leave,
    extraSubject_absent: highSchool.second_attendance?.extra_subject_absent,
    totalClass_days: highSchool.second_attendance?.total_class_days,
    isPerfect: highSchool.second_attendance?.is_perfect,
    description: highSchool.second_attendance?.description,
  },
  thirdAttendence: {
    diseaseSchoolAbsent: highSchool.third_attendance?.disease_school_absent,
    diseaseTardy: highSchool.third_attendance?.disease_tardy,
    diseaseLeave: highSchool.third_attendance?.disease_leave,
    diseaseSubject_absent: highSchool.third_attendance?.disease_subject_absent,
    unauthorizedSchoolAbsent: highSchool.third_attendance?.unauthorized_school_absent,
    unauthorizedTardy: highSchool.third_attendance?.unauthorized_tardy,
    unauthorizedLeave: highSchool.third_attendance?.unauthorized_leave,
    unauthorizedSubject_absent: highSchool.third_attendance?.unauthorized_subject_absent,
    extraSchoolAbsent: highSchool.third_attendance?.extra_school_absent,
    extraTardy: highSchool.third_attendance?.extra_tardy,
    extraLeave: highSchool.third_attendance?.extra_leave,
    extraSubject_absent: highSchool.third_attendance?.extra_subject_absent,
    totalClass_days: highSchool.third_attendance?.total_class_days,
    isPerfect: highSchool.third_attendance?.is_perfect,
    description: highSchool.third_attendance?.description,
  },
  major: highSchool.major,
  grade: highSchool.grade,
  etc: highSchool.etc,
});
