import { ResumeHighSchoolDef } from "../type";

export const selector = (highschoolArr: ResumeHighSchoolDef[]) =>
  highschoolArr.map((highschool) => ({
    data: {
      id: highschool.id,
      name: highschool.name,
      graduateType: highschool.graduate_type,
      isAlternative_test: highschool.is_alternative_test,
      startDate: highschool.start_date,
      endDate: highschool.end_date,
      firstAttendance: {
        diseaseSchoolAbsent: highschool.first_attendance?.disease_school_absent,
        diseaseTardy: highschool.first_attendance?.disease_tardy,
        diseaseLeave: highschool.first_attendance?.disease_leave,
        diseaseSubject_absent: highschool.first_attendance?.disease_subject_absent,
        unauthorizedSchoolAbsent: highschool.first_attendance?.unauthorized_school_absent,
        unauthorizedTardy: highschool.first_attendance?.unauthorized_tardy,
        unauthorizedLeave: highschool.first_attendance?.unauthorized_leave,
        unauthorizedSubject_absent: highschool.first_attendance?.unauthorized_subject_absent,
        extraSchoolAbsent: highschool.first_attendance?.extra_school_absent,
        extraTardy: highschool.first_attendance?.extra_tardy,
        extraLeave: highschool.first_attendance?.extra_leave,
        extraSubject_absent: highschool.first_attendance?.extra_subject_absent,
        totalClass_days: highschool.first_attendance?.total_class_days,
        isPerfect: highschool.first_attendance?.is_perfect,
        description: highschool.first_attendance?.description,
      },
      secondAttendance: {
        diseaseSchoolAbsent: highschool.second_attendance?.disease_school_absent,
        diseaseTardy: highschool.second_attendance?.disease_tardy,
        diseaseLeave: highschool.second_attendance?.disease_leave,
        diseaseSubject_absent: highschool.second_attendance?.disease_subject_absent,
        unauthorizedSchoolAbsent: highschool.second_attendance?.unauthorized_school_absent,
        unauthorizedTardy: highschool.second_attendance?.unauthorized_tardy,
        unauthorizedLeave: highschool.second_attendance?.unauthorized_leave,
        unauthorizedSubject_absent: highschool.second_attendance?.unauthorized_subject_absent,
        extraSchoolAbsent: highschool.second_attendance?.extra_school_absent,
        extraTardy: highschool.second_attendance?.extra_tardy,
        extraLeave: highschool.second_attendance?.extra_leave,
        extraSubject_absent: highschool.second_attendance?.extra_subject_absent,
        totalClass_days: highschool.second_attendance?.total_class_days,
        isPerfect: highschool.second_attendance?.is_perfect,
        description: highschool.second_attendance?.description,
      },
      thirdAttendence: {
        diseaseSchoolAbsent: highschool.third_attendance?.disease_school_absent,
        diseaseTardy: highschool.third_attendance?.disease_tardy,
        diseaseLeave: highschool.third_attendance?.disease_leave,
        diseaseSubject_absent: highschool.third_attendance?.disease_subject_absent,
        unauthorizedSchoolAbsent: highschool.third_attendance?.unauthorized_school_absent,
        unauthorizedTardy: highschool.third_attendance?.unauthorized_tardy,
        unauthorizedLeave: highschool.third_attendance?.unauthorized_leave,
        unauthorizedSubject_absent: highschool.third_attendance?.unauthorized_subject_absent,
        extraSchoolAbsent: highschool.third_attendance?.extra_school_absent,
        extraTardy: highschool.third_attendance?.extra_tardy,
        extraLeave: highschool.third_attendance?.extra_leave,
        extraSubject_absent: highschool.third_attendance?.extra_subject_absent,
        totalClass_days: highschool.third_attendance?.total_class_days,
        isPerfect: highschool.third_attendance?.is_perfect,
        description: highschool.third_attendance?.description,
      },
      major: highschool.major,
      grade: highschool.grade,
      etc: highschool.etc,
    },
  }));
