export const BLANK_JD = {
  detail: {
    task_main: "",
    task_sub: [],
    task_description: "",
    contract_type: "",
    conversion_rate: null,
    hire_number: 0,
    pay: "",
    shift: [],
    place: {
      is_undefined: false,
      etc: null,
      data: [],
    },
  },
  qualification: {
    highschool: false,
    college: false,
    university: false,
    required_etc: null,
    required_experience: "",
    required_min_year: null,
    required_max_year: null,
    preferred_certification: [],
    preferred_etc: null,
  },
  apply: {
    start_time: "",
    end_time: "",
    document: "",
    etc: null,
    process: "",
    route: { is_direct: true, link: null, email: null },
    cut: false,
  },
};
