name: gocho_web 사이트맵 생성
on:
  pull_request:
    branches: [main, dev]
jobs:
  creator_sitemap:
    name: 사이트맵 생성
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: pnpm 초기 설정
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: pnpm 디렉터리 확인
        id: pnpm-directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: pnpm 캐시 가져오기
        with:
          path: ${{ steps.pnpm-directory.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: dependency 설치
        run: pnpm install --frozen-lockfile

      - name: 고초웹 사이트맵 실행
        run: cd apps/gocho_web && pnpm sitemap
